import React from 'react'
import styled from 'styled-components'

const LoaderIcon = () => {
  return (
    <Container>
      <svg viewBox="0 0 500 500">
        <polygon points="118 253,137 193,4 254" style={{ fill: "rgb(163, 42, 96)" }} className="svg-elem-1">
        </polygon>
        <polygon points="37 154,137 193,4 254" style={{ fill: "rgb(230, 56, 9}3)" }} className="svg-elem-2">
        </polygon>
        <polygon points="37 154,137 193,113 117" style={{ fill: "rgb(240, 72, 131)" }} className="svg-elem-3" >
        </polygon >
        <polygon points="37 154,80 24,113 117" style={{ fill: "rgb(242, 134, 183" }} className="svg-elem-4" >
        </polygon >
        <polygon points="231 80,89 6,209 5" style={{ fill: "rgb(131, 208, 226)" }} className="svg-elem-5" >
        </polygon >
        <polygon points="231 80,89 6,139 147" style={{ fill: "rgb(0, 177, 207)" }} className="svg-elem-6" >
        </polygon >
        <polygon points="231 80,176 250,139 147" style={{ fill: "rgb(74, 164, 191)" }} className="svg-elem-7">
        </polygon >
        <polygon points="231 80,176 250,276 210" style={{ fill: "rgb(45, 122, 166)" }} className="svg-elem-8" >
        </polygon >
        <polygon points="289 250,176 250,276 210" style={{ fill: "rgb(34, 58, 122)" }} className="svg-elem-9" >
        </polygon >

        <polygon points="289 250,276 210,311 196" style={{ fill: "rgb(57, 137, 64)" }} className="svg-elem-10" >
        </polygon >
        <polygon points="248 132,276 210,311 196" style={{ fill: "rgb(94, 170, 70)" }} className="svg-elem-11" >
        </polygon >
        <polygon points="252 21,231 80,251 140,311 196" style={{ fill: "rgb(154, 196, 60)" }} className="svg-elem-12" >
        </polygon >

        <polygon points="408 93,378 5,261 6" style={{ fill: "rgb(255, 216, 63)" }} className="svg-elem-13" >
        </polygon >
        <polygon points="408 93,313 149,261 6" style={{ fill: "rgb(251, 177, 70)" }} className="svg-elem-14" >
        </polygon >
        <polygon points="408 93,313 149,440 187" style={{ fill: "rgb(249, 146, 51)" }} className="svg-elem-15" >
        </polygon >
        <polygon points="348 251,313 149,440 187" style={{ fill: "rgb(239, 73, 61)" }} className="svg-elem-16" >
        </polygon >
        <polygon points="348 251,462 251,440 187" style={{ fill: "rgb(209, 44, 42)" }} className="svg-elem-17" >
        </polygon >
      </svg >
    </Container >
  )
}

export default LoaderIcon

const Container = styled.div`
    width: 20rem;
    svg{
        width: 100%;
        height: 100%;
    }

    @media(max-width:768px) {
      width: 10rem;
    }
    /***************************************************
 * Generated by SVG Artista on 1/10/2023, 2:21:23 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/***************************************************
 * Generated by SVG Artista on 1/10/2023, 2:55:56 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

/***************************************************
 * Generated by SVG Artista on 1/19/2023, 5:16:08 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(163, 42, 96);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(163, 42, 96);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.8s linear 0.3s both;
          animation: animate-svg-fill-1 0.8s linear 0.3s both;
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(230, 56, 93);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(230, 56, 93);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.8s linear 0.36s both;
          animation: animate-svg-fill-2 0.8s linear 0.36s both;
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(240, 72, 131);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(240, 72, 131);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.8s linear 0.42s both;
          animation: animate-svg-fill-3 0.8s linear 0.42s both;
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(242, 134, 183);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(242, 134, 183);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-fill-4 0.8s linear 0.48s both;
          animation: animate-svg-fill-4 0.8s linear 0.48s both;
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(131, 208, 226);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(131, 208, 226);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-fill-5 0.8s linear 0.54s both;
          animation: animate-svg-fill-5 0.8s linear 0.54s both;
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 177, 207);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 177, 207);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-fill-6 0.8s linear 0.6s both;
          animation: animate-svg-fill-6 0.8s linear 0.6s both;
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(74, 164, 191);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(74, 164, 191);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-fill-7 0.8s linear 0.6599999999999999s both;
          animation: animate-svg-fill-7 0.8s linear 0.6599999999999999s both;
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(45, 122, 166);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(45, 122, 166);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-fill-8 0.8s linear 0.72s both;
          animation: animate-svg-fill-8 0.8s linear 0.72s both;
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(34, 58, 122);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(34, 58, 122);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-fill-9 0.8s linear 0.78s both;
          animation: animate-svg-fill-9 0.8s linear 0.78s both;
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(57, 137, 64);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(57, 137, 64);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-fill-10 0.8s linear 0.8400000000000001s both;
          animation: animate-svg-fill-10 0.8s linear 0.8400000000000001s both;
}

@-webkit-keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(94, 170, 70);
  }
}

@keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(94, 170, 70);
  }
}

.svg-elem-11 {
  -webkit-animation: animate-svg-fill-11 0.8s linear 0.8999999999999999s both;
          animation: animate-svg-fill-11 0.8s linear 0.8999999999999999s both;
}

@-webkit-keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(154, 196, 60);
  }
}

@keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(154, 196, 60);
  }
}

.svg-elem-12 {
  -webkit-animation: animate-svg-fill-12 0.8s linear 0.96s both;
          animation: animate-svg-fill-12 0.8s linear 0.96s both;
}

@-webkit-keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 216, 63);
  }
}

@keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(255, 216, 63);
  }
}

.svg-elem-13 {
  -webkit-animation: animate-svg-fill-13 0.8s linear 1.02s both;
          animation: animate-svg-fill-13 0.8s linear 1.02s both;
}

@-webkit-keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(251, 177, 70);
  }
}

@keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(251, 177, 70);
  }
}

.svg-elem-14 {
  -webkit-animation: animate-svg-fill-14 0.8s linear 1.08s both;
          animation: animate-svg-fill-14 0.8s linear 1.08s both;
}

@-webkit-keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(249, 146, 51);
  }
}

@keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(249, 146, 51);
  }
}

.svg-elem-15 {
  -webkit-animation: animate-svg-fill-15 0.8s linear 1.14s both;
          animation: animate-svg-fill-15 0.8s linear 1.14s both;
}

@-webkit-keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 73, 61);
  }
}

@keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(239, 73, 61);
  }
}

.svg-elem-16 {
  -webkit-animation: animate-svg-fill-16 0.8s linear 1.2s both;
          animation: animate-svg-fill-16 0.8s linear 1.2s both;
}

@-webkit-keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(209, 44, 42);
  }
}

@keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(209, 44, 42);
  }
}

.svg-elem-17 {
  -webkit-animation: animate-svg-fill-17 0.8s linear 1.26s both;
          animation: animate-svg-fill-17 0.8s linear 1.26s both;
}

`