export { default as AmazonImage } from './amazonclone.png'
export { default as AmazonIamgeSmall } from './amazonclonesqr.png'
export { default as ShreeJewellerImage } from './shreejeweller.png'
export { default as ShreeJewellerImageSmall } from './shreejewellersqr.png'
export { default as TvastraImage } from './tvastra.png'
export { default as TvastraImageSmall } from './tvastrasqr.png'