export { default as AmazonImage } from './amazonclone.jpg'
export { default as AmazonIamgeSmall } from './amazonclonesqr.jpg'
export { default as ShreeJewellerImage } from './shreejeweller.jpg'
export { default as ShreeJewellerImageSmall } from './shreejewellersqr.jpg'
export { default as TvastraImage } from './tvastra.jpg'
export { default as TvastraImageSmall } from './tvastrasqr.jpg'